### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by kilonzi**
PR request for a merge to master after extensive application of bootstrap classes and css

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
> ### Pull request under review by Ahmed Mahfoudh
### Great work :clap: . However, some changes needs to be made in order for us to approve your project. check below :arrow_down: 

#### Implementation details

* [x] It refrences [Bootstrap CSS file](https://getbootstrap.com/docs/4.3/getting-started/introduction/#css)
  - You only need to reference the minified bootstrap file. the js scripts are extra for this project.  
  - In the live preview it shows the page not styled. I think you have a problem referencing the css files.
image

- **[REQUIRED]** add a live preview of the project to your README.md file.

### That's it :relaxed: . When finished, kindly resubmit another code review request :pray:

**Comment by kilonzi** [comment]
@stratospherique I have amended as required (https://htmlpreview.github.io/?https://github.com/kilonzi/newsweek/blob/homepage/index.html) - Also notice that 
Screenshot 2019-10-10 at 17 44 18
Github is blocking some crucial CSS styles from been applied.

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work :clap: . However, some requirements needs to be implemented in order for us to make your project approved. check below :arrow_down:  

#### Page structure

##### Navigation bar

* [x] It contains main navigation links.
  - They are plain text, :pray: make them as links.

##### Main content

* [x] **It changes with RWD breakpoints.**
image
  - The main content is not responsive. :pray: fix it.

##### Footer

* [x] It contains main navigation links.
  - They are plain text, :pray: make them as links.
* [x] **It changes with RWD breakpoints.**
  - This is also not responsive.

#### Implementation details

* [x] It uses Bootstrap Css classes **everywhere** for styling ( for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options) )
   - In order to make your page resonsive, you need to use classes like `col-md-N`,`com-sm-N`, etc. Check bootstrap documentation for more info.

### That's it :relieved: . When finished, kindly resubmit another code review form :pray: .

**Comment by kilonzi** [comment]
@stratospherique  Resolved RWD breakpoints

**Comment by ebukaume** [comment]
Hi @kilonzi :wave: 

Nice job implementing the requested changes. :+1: 

**Congratulations :champagne: , you can go ahead and merge this branch.** Don't forget to add a link to the live page in your README file.


Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Pull request merged**
